### ISSUE TITLE
libraryDependencies issue 

### ISSUE THREAD

**Issue by AltiumHanChou** [freechipsproject/firrtl-interpreter#220]
Hi ~
I try to use this firrtl-interpreter.
But I got version issue (firrtl-interpreter, scalatest_2.11 and) so that I can't download library Dependencies which firrtl-interpreter needs.

build.sbt : 

```
libraryDependencies ++= Seq(
  "edu.berkeley.cs" %% "chisel3" % chiselVersion,
  "edu.berkeley.cs" %% "chisel-iotesters" % "1.0",
  "edu.berkeley.cs" %% "firrtl-interpreter" % "0.1-SNAPSHOT",
  "org.scalatest" % "scalatest_2.11" % "2.2.4",
  "org.scalacheck" %% "scalacheck" % "1.12.4")
```

Should I change version to the latest one ? or some specific version? 
(I try put all the version to the latest, but it seem it didn't work)

**Comment by schoeberl** [comment]
Maybe it is better to use treadle, as firrtl-interpreter will be deprecated.

https://github.com/chipsalliance/treadle

**Comment by AltiumHanChou** [comment]
@schoeberl  OK, I got it. Thank you for your information.
